### PR TITLE
lib: add australia libnative-lib.so

### PR DESCRIPTION
**Pull request by bitnimble**
pulled from Australian bluelink `com.hyundai.bluelink.aus`

### CODE REVIEW

**Comment by Hacksore** [comment]
This works without any code change? that's shocking haha.

Could you update these for me so that it tags the image as `arm-au` then we can have the docker update as well.

add `arm-au`
https://github.com/Hacksore/hyundai-kia-stamp/blob/arm-au/.github/workflows/ci.yaml#L7

change to `arm-au`
https://github.com/Hacksore/hyundai-kia-stamp/blob/arm-au/.github/workflows/ci.yaml#L55-L56

**Review by Hacksore — CHANGES_REQUESTED** [review]
Once the CI code is updated ill merge it in.

**Comment by bitnimble** [comment]
i'm not super familiar with GH actions, will you be copying this over to the master branch? these are global right?

if so i'll also have to update `if: ${{ github.ref == 'refs/heads/arm' }}` to additionally include `arm-au` branch?

**Comment by bitnimble** [comment]
ah derp nvm, it's a hook that happens on push and triggers workflows for that branch, ignore me

**Comment by Hacksore** [comment]
Well I believe we have to make the CI changes on the default branch so the prolly doesn't harm anything just means I'll have to refactor the default branch 😬.

Working on this now.

**Pull request merged**
